config/routes.rb
Rails.application.routes.draw do
  get 'address_hists/create'
  get 'ordered_items/create'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
  }
  resources :users do
      get :mypage
  end
  resources :ad_shopping_hists, only: [:index, :show, :update]
  resources :infos, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :ad_items
  resources :ad_users, only: [:index, :edit, :update, :destroy]
  get 'top' => 'ad_users#top', as:'ad_top'
  resources :shopping_hists, only: [:index, :create, :show]
  resources :ordered_items, only: [:create]
  resources :address_hists, only: [:create]
  resources :carts, only: [:index, :create, :destroy, :update]
  get 'cart_cmp' => 'carts#cart_cmp', as:'cart_cmp'
  get 'cart_cfm' => 'carts#cart_cfm', as:'cart_cfm'
  resources :items, only: [:index, :show]
  resources :users, only: [:show, :update, :edit]
  get 'resign' => 'users#resign', as:'resign'
  get 'resign_cmp' => 'users#resign', as:'resign_cmp'
  root to: 'users#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
   belongs_to :user
end

app/models/address_history.rb
class AddressHistory < ApplicationRecord
    belongs_to :shopping_history,optional: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
    has_many :items, dependent: :destroy
end

app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :user
    belongs_to :item
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_one :item, dependent: :destroy
end

app/models/infomation.rb
class Infomation < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :property
    belongs_to :artist
    belongs_to :genre
    belongs_to :label

    has_many :musics, dependent: :destroy
    accepts_nested_attributes_for :musics, allow_destroy: true
    has_many :ordered_items, dependent: :destroy

    attachment :jacket
    end

app/models/label.rb
class Label < ApplicationRecord
    has_one :item, dependent: :destroy
end

app/models/music.rb
class Music < ApplicationRecord
    belongs_to :item
end

app/models/ordered_item.rb
class OrderedItem < ApplicationRecord
    belongs_to :shopping_history,optional: true
    belongs_to :item,optional: true
end

app/models/property.rb
class Property < ApplicationRecord
    has_one :item, dependent: :destroy
end

app/models/shopping_history.rb
class ShoppingHistory < ApplicationRecord
	belongs_to :user
    has_one :address_history, dependent: :destroy
    accepts_nested_attributes_for :address_history, allow_destroy: true
    has_many :ordered_items, dependent: :destroy
    accepts_nested_attributes_for :ordered_items, allow_destroy: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  acts_as_paranoid
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
  has_one :address, dependent: :destroy
  accepts_nested_attributes_for :address
  before_create :build_default_address

  has_many :carts, dependent: :destroy
  has_many :shopping_histories, dependent: :destroy
  private
  def build_default_address
    build_address
    true
  end
end

app/controllers/ad_users_controller.rb
class AdUsersController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_user_admin
  def top
    @user = User.find(current_user.id)
  end

  def index
    @users = User.all
    @user = User.find(current_user.id)
    @shopping_hists = ShoppingHistory.all
    @users = @users.page(params[:page]).per(20)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
        flash[:notice] = "ユーザー情報が更新されました。"
        redirect_to ad_users_path
    else
      flash[:notice] = "ユーザー情報が正しく更新されませんでした。"
      redirect_to root_path
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      flash[:notice] = "削除が正常に完了しました。"
      redirect_to ad_users_path
    else
      flash[:notice] = "削除に失敗しました。"
      redirect_to ad_users_path
    end
  end

  private
  def user_params
    params.require(:user).permit(:kanji_last,:kanji_first,:katakana_last,:katakana_first,:phone_number,:email,:notice,address_attributes: [:postcode,:prefecture,:city,:street,:building])
  end
end

app/helpers/ad_items_helper.rb
module AdItemsHelper
end

app/helpers/ad_users_helper.rb
module AdUsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ad_users/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-1">
		</div>
		<div class="col-lg-10">
			<h2>ユーザー編集画面</h2>
			<p><%= link_to "ユーザー一覧画面へ",ad_users_path,method: :get %></p>
			<div class="form_for">
				<%= form_for @user, url:ad_user_path(@user.id) do |f|%>
				<p>名前(姓名)</p>
				<div class="kanji_name">
					<%=f.label :姓%>
					<%=f.text_field :kanji_last%>
					<%=f.label :名%>
					<%=f.text_field :kanji_first%>
				</div>
				<div class="katakana_name">
					<p>名前（カナ）</p>
					<%=f.label :姓%>
					<%=f.text_field :katakana_last%>
					<%=f.label :名%>
					<%=f.text_field :katakana_first%>
				</div>
				<div class="addresses">
					<%= f.fields_for :address do |a| %>
						<p>住所</p>
						<%=a.label :郵便番号%><br>
						<%=a.text_field :postcode%><br>
						<%=a.label :県%><br>
						<%=a.text_field :prefecture%><br>
						<%=a.label :市区町村%><br>
						<%=a.text_field :city%><br>
						<%=a.label :番地%><br>
						<%=a.text_field :street%><br>
						<%=a.label :建物名%><br>
						<%=a.text_field :building%>
					<% end %>
					<div class="phone_email">
						<%= f.label :電話番号 %><br>
						<%= f.text_field :phone_number %><br>
						<%= f.label :メールアドレス %><br>
						<%= f.text_field :email %><br>
					</div>
					<div class="notice">
						<%= f.label :カスタマーセンターからのお知らせ %><br>
						<%= f.text_area :notice %>
					</div>
					<%= f.submit "編集完了" %>
				</div>
				<% end %>
			</div>
		</div>
		<div class="col-lg-1">
		</div>
	</div>
</div>

app/views/ad_users/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-1">
		</div>
		<div class="col-lg-10">
			<% if flash[:notice] %>
			<%= flash[:notice] %>
			<% end %>
			<h2>ユーザー管理画面</h2>
			<p><%= link_to "購入履歴一覧画面へ", ad_shopping_hists_path %></p>
			<table class="table">
				<thead>
					<tr>
						<th>名前</th>
						<th>メールアドレス</th>
						<th>電話番号</th>
						<th>総額</th>
						<th></th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<% @users.find_each do |user| %>
					<tr>
						<td><%= user.kanji_last %><%= user.kanji_first %></td>
						<td><%= user.email%></td>
						<td><%= user.phone_number%></td>
						<td>
							<% result = 0 %>
							<% @shopping_hists.where(:user_id => user.id).find_each do |s| %>
								<% s.ordered_items.each do |o| %>
									<% result += o.price * o.quantity %>
								<% end %>
							<% end %>
							<%= number_to_yen(result) %>
						</td>
						<td><%= link_to '編集', edit_ad_user_path(user.id)%></td>
						<td><%= link_to '削除', ad_user_path(user.id), method: :delete, data: {confirm: '削除してよろしいですか？'} %>
						</td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
		<div class="margin_0">
			<%= paginate @users %>
		</div>
		<div class="col-lg-1">
		</div>
	</div>
</div>

app/views/ad_users/top.html.erb
<div class="container">
	<div class="row" style="margin-top: 100px;">
		<div class="col-lg-3"></div>
		<div class="col-lg-6">
			<div class="text-center">
			  <%= link_to "商品管理画面へ", ad_items_path %>
			  <br><%= link_to "ユーザー管理画面へ", ad_users_path %>
			  <br><%= link_to "お知らせ管理画面へ", infos_path %>

		    </div>
		</div>
		<div class="col-lg-3"></div>

	</div>
</div>