config/routes.rb
Rails.application.routes.draw do
  get 'address_hists/create'
  get 'ordered_items/create'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
  }
  resources :users do
      get :mypage
  end
  resources :ad_shopping_hists, only: [:index, :show, :update]
  resources :infos, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :ad_items
  resources :ad_users, only: [:index, :edit, :update, :destroy]
  get 'top' => 'ad_users#top', as:'ad_top'
  resources :shopping_hists, only: [:index, :create, :show]
  resources :ordered_items, only: [:create]
  resources :address_hists, only: [:create]
  resources :carts, only: [:index, :create, :destroy, :update]
  get 'cart_cmp' => 'carts#cart_cmp', as:'cart_cmp'
  get 'cart_cfm' => 'carts#cart_cfm', as:'cart_cfm'
  resources :items, only: [:index, :show]
  resources :users, only: [:show, :update, :edit]
  get 'resign' => 'users#resign', as:'resign'
  get 'resign_cmp' => 'users#resign', as:'resign_cmp'
  root to: 'users#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  acts_as_paranoid
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
  has_one :address, dependent: :destroy
  accepts_nested_attributes_for :address
  before_create :build_default_address

  has_many :carts, dependent: :destroy
  has_many :shopping_histories, dependent: :destroy
  private
  def build_default_address
    build_address
    true
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    @user = User.new
    @noadmin = User.where('admin_user = ?', true).empty?
    super
  end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  def destroy
    super
    resource.email = DateTime.now.to_s + '@削除済み'
    resource.save
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def top
    @items = Item.all
    @infos = Infomation.all

    if user_signed_in?
      @user = User.find(current_user.id)
    else

    end
  end

  def mypage
    @shopping_histories = ShoppingHistory.all
    @shopping_history = @shopping_histories.where(:user_id => current_user)
  end

  def show
    if user_signed_in?
      @user = User.find(current_user.id)
    end
  end

  def update
    if user_signed_in?
      @user = User.find(current_user.id)
    end
    if @user.update(user_params)
        flash[:notice] = "ユーザー情報が更新されました。"
        redirect_to user_mypage_path(current_user)
    else
      flash[:notice] = "ユーザー情報が正しく更新されませんでした。"
      redirect_to user_mypage_path(current_user)
    end
  end

  def edit
    if user_signed_in?
      @user = User.find(current_user.id)
    end
  end

  def resign
  end

  def resign_cmp
  end

  private
  def user_params
    params.require(:user).permit(:kanji_last,:kanji_first,:katakana_last,:katakana_first,:phone_number,:email,:notice,address_attributes: [:postcode,:prefecture,:city,:street,:building])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_footer.html.erb
<div id="wrapper">
    <footer id="footer">
    <div class="block_30"></div>
        <p>Copyright © 2019 NaganoEC All Rights Reserved.</p>
    </footer>
</div>

app/views/users/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col-12"><br><br>
            <h3 class="margin_top"><strong>お客様情報編集画面</strong></h3><br>
            <div class="row margin_top">
                <%= form_for @user, method: :patch  do |f| %>
                <p class=""><strong>お名前</strong></p>
                <div class="">
                    <%= f.text_field :kanji_last %><%= f.text_field :kanji_first %>
                </div><br>
                <p class=""><strong>フリガナ</strong></p>
                <div class="">
                    <%= f.text_field :katakana_last %><%= f.text_field :katakana_first %>
                </div><br>
                <p class=""><strong>電話番号</strong></p>
                <div class="">
                    <%= f.text_field :phone_number %>
                </div><br>
                <p class=""><strong>Eメールアドレス</strong></p>
                <div class="">
                    <%= f.text_field :email %>
                </div><br>

                <div class="addresses">
                    <%= f.fields_for :address do |a| %>
                    <div class="">
                    <p class=""><strong>郵便番号</strong></p>
                        <%= a.text_field :postcode %>
                    </div><br>
                    <p class=""><strong>都道府県</strong></p>
                    <div class="">
                        <%= a.text_field :prefecture %>
                    </div><br>
                    <p class=""><strong>市区町村</strong></p>
                    <div class="">
                        <%= a.text_field :city %>
                    </div><br>
                    <p class=""><strong>番地</strong></p>
                    <div class="">
                        <%= a.text_field :street %>
                    </div><br>
                    <p class=""><strong>物件名</strong></p>
                    <div class="">
                        <%= a.text_field :building %>
                    </div><br>
                    <% end %>
                </div>
                <%= link_to "戻る", :back %>
                <%= f.submit "編集完了" %>

                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/users/mypage.html.erb
<div class="container">
    <div class="row">
        <div class="col-12">
            <%if flash[:notice]%>
        <%=flash[:notice]%>
        <% end %>
            <div class="block_30"></div>
                <%if flash[:notice]%>
                    <%=flash[:notice]%>
                <% end %>
            <h2><strong><%= current_user.try(:kanji_last) %> <%= current_user.try(:kanji_first) %> 様の MyPage</strong>
            </h2>
            <p>※パスワードは定期的に更新されることをおすすめします。</p>
            <br>
            <br>
            <div class="border-bottom"></div>
            <br>
            <h3><strong>Infomation</strong></h3>
            <p>カスタマーデスクからのお知らせ。</p>
            <div class="notice_user"><%= current_user.try(:notice) %></div>
            <div class="block_30"></div>
            <div class="border-bottom"></div>
            <br>

            <h3><strong>発送情報</strong></h3>
            <p>購入された商品の発送状況、２件まで表示されます。他をご確認したい場合は購入履歴をご確認ください。</p>
            <% @shopping_history.last(2).each do |sh| %>
            <div class="sh_field mp_firld_margin padding_left10px padding_bottom10px">
                <div class="row">
                    <div class="col-6">
                        購入日：<%= sh.shopping_date.strftime('%Y年%m月%d日') %>　<%= sh.status %>
                    </div>
                    <div class="col-6 text_right padding_right30px">
                    </div>
                </div>
                <div class="block_10"></div>
                <% sh.ordered_items.each do |oi| %>
                <%= attachment_image_tag oi.item, :jacket, size:"100x100",class:"margin_bottom5px" %>
                <% end %>
            </div>
            <% end %>

            <div class="border-bottom"></div>
            <div class="mypage_field3 padding_top10px margin_top padding_left10px">
                <%= link_to "購入履歴", shopping_hists_path(current_user.id) %>
            </div>
            <div class="mypage_field3 padding_top10px margin_top padding_left10px">
                <%= link_to "お客様基本情報確認", user_path(current_user.id) %>
            </div>
            <div class="mypage_field3 padding_top10px margin_top padding_left10px">
                <%= link_to "退会", edit_user_registration_path %>
            </div>


        </div>

    </div>

app/views/users/resign_cmp.html.erb
<h1>Users#resign_cmp</h1>
<p>Find me in app/views/users/resign_cmp.html.erb</p>

app/views/users/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-1"></div>
        <div class="col-9"><br><br>
            <h3 class="margin_top"><strong>お客様情報確認画面</strong></h3><br>
            <div class="row margin_top">
                <p class="col-2"><strong>登録日時</strong></p>
                <div class="col-10">
                    <%= @user.created_at.strftime('%Y年%m月%d日 %H:%M') %>
                </div>
                <p class="col-2"><strong>お名前</strong></p>
                <div class="col-10">
                    <%= @user.kanji_last %><%= @user.kanji_first %>
                </div>
                <p class="col-2"><strong>電話番号</strong></p>
                <div class="col-10">
                    <%= @user.phone_number %>
                </div>
                <p class="col-2"><strong>Eメール</strong></p>
                <div class="col-10">
                    <%= @user.email %>
                </div>
                <p class="col-2"><strong>登録住所</strong></p>
                <div class="col-10">
                    <%= @user.address.postcode %>
                </div>
                <p class="col-2"><strong>都道府県</strong></p>
                <div class="col-10">
                    <%= @user.address.prefecture %>
                </div>
                <p class="col-2"><strong>市区町村</strong></p>
                <div class="col-10">
                    <%= @user.address.city %>
                </div>
                <p class="col-2"><strong>番地</strong></p>
                <div class="col-10">
                    <%= @user.address.street %>
                </div>
                <p class="col-2"><strong>物件名</strong></p>
                <div class="col-10">
                    <%= @user.address.building %>
                </div>
                <%= link_to "戻る", :back %>
                <%= link_to "　　　　　　編集　　　　　　",edit_user_path(current_user.id),class: "btn btn-info margin_0" %>
            </div>
            <div class="col-1"></div>
        </div>
    </div>

app/views/users/top.html.erb
<div class="block_20"></div>
<div class="container">
	<div class="row">
		<div class="col-12 background_img">
			<div class='wave -one'></div>
			<div class='wave -two'></div>
			<div class='wave -three'></div>
			<div class='title'>NaganoEC</div>
			<div class="row">
				<div class="col-3">
					<div class="slider">
						<% @items[0..100].each do |i| %>
						<div><%= attachment_image_tag i, :jacket, fallback: "no_image.jpg" %></div>
						<% end %>
					</div>
				</div>
				<div class="col-9">
					<h2 class="color_white re_text">HOT ITEM</h2>
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="sasa">
			<h3>新規商品</h3>
		</div>
		<div class="color_red"><span>NEW ARRIVAL</span></div>
		<div class="block_20"></div>
		<% @items.last(5).each do |i| %>
		<%= link_to item_path(i), class: "item_index color_black" do %>

		<div class="item_index">
			<table>
				<tbody>
					<tr>
						<td><br><%= attachment_image_tag i, :jacket, fallback: "no_image.jpg", size: "200x200" %></td>
					</tr>
					<tr>
						<td><%= i.property.property %></td>
					</tr>
					<tr>
						<td><%= i.artist.artist_name %></td>
					</tr>
					<tr>
						<td><%= i.details %></td>
					</tr>
				</tbody>
			</table>
		</div>
		<% end %>
		<% end %>
	</div>
	<div class="row">
	</div>
	<div class="block_30"></div>
	<div class="row">
		<div class="info_user">
			<h3>お知らせ</h3>
		</div>
		<div class="color_red"><span>INFORMATION</span></div>
		　　<% @infos[0..4].each do |i| %>
		<div class="infos_table">
			<table class="table">
				<tbody>
					<tr>
						<td><%= i.infomation %></td>
						<td></td>
						<td class="infos_span"><%= i.created_at.strftime("%Y-%m-%d") %></td>
					</tr>
				</tbody>
			</table>
			<% end %>
		</div>
	</div>

</div>