config/routes.rb
Rails.application.routes.draw do
  get 'address_hists/create'
  get 'ordered_items/create'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
  }
  resources :users do
      get :mypage
  end
  resources :ad_shopping_hists, only: [:index, :show, :update]
  resources :infos, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :ad_items
  resources :ad_users, only: [:index, :edit, :update, :destroy]
  get 'top' => 'ad_users#top', as:'ad_top'
  resources :shopping_hists, only: [:index, :create, :show]
  resources :ordered_items, only: [:create]
  resources :address_hists, only: [:create]
  resources :carts, only: [:index, :create, :destroy, :update]
  get 'cart_cmp' => 'carts#cart_cmp', as:'cart_cmp'
  get 'cart_cfm' => 'carts#cart_cfm', as:'cart_cfm'
  resources :items, only: [:index, :show]
  resources :users, only: [:show, :update, :edit]
  get 'resign' => 'users#resign', as:'resign'
  get 'resign_cmp' => 'users#resign', as:'resign_cmp'
  root to: 'users#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
   belongs_to :user
end

app/models/address_history.rb
class AddressHistory < ApplicationRecord
    belongs_to :shopping_history,optional: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
    has_many :items, dependent: :destroy
end

app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :user
    belongs_to :item
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_one :item, dependent: :destroy
end

app/models/infomation.rb
class Infomation < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :property
    belongs_to :artist
    belongs_to :genre
    belongs_to :label

    has_many :musics, dependent: :destroy
    accepts_nested_attributes_for :musics, allow_destroy: true
    has_many :ordered_items, dependent: :destroy

    attachment :jacket
    end

app/models/label.rb
class Label < ApplicationRecord
    has_one :item, dependent: :destroy
end

app/models/music.rb
class Music < ApplicationRecord
    belongs_to :item
end

app/models/ordered_item.rb
class OrderedItem < ApplicationRecord
    belongs_to :shopping_history,optional: true
    belongs_to :item,optional: true
end

app/models/property.rb
class Property < ApplicationRecord
    has_one :item, dependent: :destroy
end

app/models/shopping_history.rb
class ShoppingHistory < ApplicationRecord
	belongs_to :user
    has_one :address_history, dependent: :destroy
    accepts_nested_attributes_for :address_history, allow_destroy: true
    has_many :ordered_items, dependent: :destroy
    accepts_nested_attributes_for :ordered_items, allow_destroy: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  acts_as_paranoid
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
  has_one :address, dependent: :destroy
  accepts_nested_attributes_for :address
  before_create :build_default_address

  has_many :carts, dependent: :destroy
  has_many :shopping_histories, dependent: :destroy
  private
  def build_default_address
    build_address
    true
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
# カート画面を表示する
  def index
    @carts = Cart.all.includes(:item,:user)
  end
#カートテーブルに1レコード記録する(カートに入れる)
  def create
    @cart = Cart.new(cart_params)
    @cart.save
    redirect_to carts_path
  end
# 決算確認画面表示
  def cart_cfm
    @carts = Cart.all.includes(:item,:user)
    @shopping_hist = ShoppingHistory.new
      @shopping_hist.build_address_history
      @shopping_hist.ordered_items.build
    @items = Item.all
  end
#カートテーブルの特定のレコードを更新する
  def destroy
    @cart = Cart.find(params[:id])
    if @cart.destroy
      flash[:notice] = "削除しました。"
      redirect_to carts_path
    else
      flash[:notice] = "更新に失敗しました。"
      redirect_to carts_path
    end
  end
#カートテーブルの個数を更新する
  def update
    @cart = Cart.find(params[:id])
    if params[:cart][:amount].to_i <= @cart.item.stock
      @cart.update(cart_params)
      flash[:notice] = "更新しました。"
      redirect_to carts_path
    else
      flash[:notice] = "購入希望数の在庫が確保できなかったため更新に失敗しました"
      redirect_to carts_path
    end
end
#決算完了画面
  def cart_cmp
  end

  private
  def cart_params
    params.require(:cart).permit(:user_id,:item_id,:amount)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @q = Item.search(search_params)
    @items = @q.result.includes(:artist,:label,:genre,:property,:musics)
    @items = @items.page(params[:page]).per(28)
    header_name_display
  end

  def show
    @item = Item.find(params[:id])
    @cart = Cart.new
  end

private

def search_params
    params.require(:q).permit(:name_cont)
end

end

app/helpers/ad_items_helper.rb
module AdItemsHelper
end

app/helpers/ad_users_helper.rb
module AdUsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/index.html.erb
<div class="container">
	<div class="row">
		<div class="block_50"></div>
		<h2 class=""><strong>商品検索結果画面</strong></h2>
		<div class="block_20"></div>
	</div>
	<div class="row">

		<% @items.each do |item| %>
			<div class="ad_items_index_table color_black">
				<%= link_to item_path(item), class: "item_index color_black" do %>
					<div class="item_index_field border">
						<td class="border">
							<%= attachment_image_tag item, :jacket, :fill, 230, 230 , fallback: "no_image.jpg",size:'230x230' %>
						</td>
						<div class="property">
							<td><%= item.property.property %></td><br>
						</div>
						<div class="color_blue">
							<td><%= item.artist.artist_name.truncate(10) %></td><br>
						</div>
						<td><%= item.name.truncate(14) %></td><br>
				<% end %>
					<% if user_signed_in? %>
						<% if current_user.admin_user? %>
							<td>
								<div class="text_right">
									<%= link_to "商品内容編集", edit_ad_item_path(item),class: "color_white btn btn-info" %>
								</div>
							</td>
						<% end %>
					<% else %>
					<% end %>

					</div>
				<div class="border-bottom"></div>
			</div>
		<% end %>
		<div class="block"></div>
		<div class="margin_0">
			<%= paginate @items %>
		</div>
	</div>
</div>

app/views/items/show.html.erb
<div class="container">
	<div class="row">
		<div class="block_10"></div>
		<div class="block_10"></div>
		<table class="table">
			<tr>
				<td>
					<div class="col">
						<%= attachment_image_tag @item, :jacket, :fill, 500, 500, fallback: "no_image.jpg",size:'400x400' %>
					</div>
				</td>
				<td>
					<div class="col">
						<div class="item_property property">
							<%= @item.property.property %>
						</div>
						<div class="block_10"></div>
						<div class="item_name">
							<h4><strong><%=@item.name%></strong></h4>
						</div>
						<div class="artist_name artist_size">
							<%= @item.artist.artist_name %>
						</div>
						<div class="block_item_show"></div>
						<div class="item_amount amount_text color_red">
							商品価格：¥<%= number_to_yen(@item.price) %>
						</div>
						<div class="block_item_show"></div>
						<div class="row">
							<div class="col">
								<div clas="item_release_date">
									RELEASE DATE：<%= @item.release_day.strftime('%Y年%m月%d日') %>
								</div>
								<div class="item_label">
									Label：<%= @item.label.label %>
								</div>
								<div class="item_genre">
									Category：<%= @item.genre.genre %>
								</div>
							</div>
							<div class="col">
								<div class="item_stock margin_left">
									在庫：<%= @item.stock %>個
								</div>
								<% if user_signed_in? %>
								<div class="item_add_cart text_right">
									<%= form_for @cart,url: carts_path, method: :post do |f| %>
										<%= f.hidden_field :user_id, :value => current_user.id %>
										<%= f.hidden_field :item_id, :value => @item.id %>
										<%= f.hidden_field :amount, :value => 1 %>
										<% if @item.stock != 0 %>
											<%= f.submit :カートに入れる, class:"btn bg_red color_white cart_btn rounded-pill" %>
										<% else %>
											<div class="btn bg_red color_white cart_btn rounded-pill"><span> 売り切れ</span></div>
										<% end %>
									<% end %>
								</div>
								<% else %>
								<div class="item_add_cart text_right">
									<%= link_to user_session_path do %>
									<p　 class="btn bg_red color_white cart_btn rounded-pill" >カートに入れる</p>
									<% end %>
								</div>
								<% end %>
								<% if user_signed_in? %>
								<% if current_user.admin_user? %>
								<div class="text_right margin_top">
									<%= link_to "商品内容編集", edit_ad_item_path,class: "color_white btn btn-info" %>
									<% end %>
									<% else %>
									<% end %>
								</div>
							</div>
						</div>
				</td>
			</tr>
		</table>
		<table class="table">
			<td>
				<div class="item_detail col-12">
					<h4><strong>商品説明</strong></h4>
					<%= simple_format(@item.details) %>
				</div>
			</td>
		</table>
		<table class="table">
			<td>
				<div class="col-12">
					<h4><strong>収録内容</strong></h4>
					<table class="table">
						<% @item.musics.each do |m| %>
						<tr>
							<td>
								<div><strong>
									DISC <%= m.cd_number %>　</strong>
									<%= m.music_order %>.
								</div>
							</td>
							<td>
								<div class="text_left">
									<%= m.music_name %>
								</div>
							</td>
							<td>
								<div class="text_left text_right">
									<%= link_to m.test_url, :target=>["_blank"]  do %>
									<%= image_tag 'youtube_icon.png',size:"40x27"%>
									<% end %>
								</div>
							</td>
						</tr>
						<% end %>
					</table>
				</div>
			</td>
		</table>
	</div>
</div>