config/routes.rb
Rails.application.routes.draw do
  get 'address_hists/create'
  get 'ordered_items/create'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'
  }
  resources :users do
      get :mypage
  end
  resources :ad_shopping_hists, only: [:index, :show, :update]
  resources :infos, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :ad_items
  resources :ad_users, only: [:index, :edit, :update, :destroy]
  get 'top' => 'ad_users#top', as:'ad_top'
  resources :shopping_hists, only: [:index, :create, :show]
  resources :ordered_items, only: [:create]
  resources :address_hists, only: [:create]
  resources :carts, only: [:index, :create, :destroy, :update]
  get 'cart_cmp' => 'carts#cart_cmp', as:'cart_cmp'
  get 'cart_cfm' => 'carts#cart_cfm', as:'cart_cfm'
  resources :items, only: [:index, :show]
  resources :users, only: [:show, :update, :edit]
  get 'resign' => 'users#resign', as:'resign'
  get 'resign_cmp' => 'users#resign', as:'resign_cmp'
  root to: 'users#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
   belongs_to :user
end

app/models/address_history.rb
class AddressHistory < ApplicationRecord
    belongs_to :shopping_history,optional: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
    has_many :items, dependent: :destroy
end

app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :user
    belongs_to :item
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_one :item, dependent: :destroy
end

app/models/infomation.rb
class Infomation < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :property
    belongs_to :artist
    belongs_to :genre
    belongs_to :label

    has_many :musics, dependent: :destroy
    accepts_nested_attributes_for :musics, allow_destroy: true
    has_many :ordered_items, dependent: :destroy

    attachment :jacket
    end

app/models/label.rb
class Label < ApplicationRecord
    has_one :item, dependent: :destroy
end

app/models/music.rb
class Music < ApplicationRecord
    belongs_to :item
end

app/models/ordered_item.rb
class OrderedItem < ApplicationRecord
    belongs_to :shopping_history,optional: true
    belongs_to :item,optional: true
end

app/models/property.rb
class Property < ApplicationRecord
    has_one :item, dependent: :destroy
end

app/models/shopping_history.rb
class ShoppingHistory < ApplicationRecord
	belongs_to :user
    has_one :address_history, dependent: :destroy
    accepts_nested_attributes_for :address_history, allow_destroy: true
    has_many :ordered_items, dependent: :destroy
    accepts_nested_attributes_for :ordered_items, allow_destroy: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  acts_as_paranoid
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
  has_one :address, dependent: :destroy
  accepts_nested_attributes_for :address
  before_create :build_default_address

  has_many :carts, dependent: :destroy
  has_many :shopping_histories, dependent: :destroy
  private
  def build_default_address
    build_address
    true
  end
end

app/helpers/ad_items_helper.rb
module AdItemsHelper
end

app/helpers/ad_users_helper.rb
module AdUsersHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Nagano</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css">
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
</head>

<body>
  <header>

    <nav class="navbar navbar-expand-lg navbar-dark bg-black">
      <a class="navbar-brand" href="/">NaganoEC</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02"
        aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <% if user_signed_in? %>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto">
          <li class="color_white">
            <%= current_user.try(:kanji_last) %> <%= current_user.try(:kanji_first) %> 様
          </li>
        </ul>
        <ul class="navbar-nav mt-2 mt-lg-0">
          <% if current_user.admin_user? %>
          <li class="nav-item li_margin">
            <%= link_to "管理者ページ", ad_top_path,class: "color_white btn btn-dark" %>
            <% end %>
          </li>
          <li class="nav-item li_margin">
            <%= link_to "　ホーム　", root_path, class: "btn btn-dark nav_margin"%>
          </li>
          <li class="nav-item li_margin">
            <%= link_to "　カート　", carts_path, class: "btn btn-dark nav_margin"%>
          </li>

          <li class="nav-item li_margin">
            <%= link_to "マイページ", user_mypage_path(current_user), class: "btn btn-dark nav_margin" %>
          </li>
          <li class="nav-item li_margin">
            <%= link_to "カート", carts_path, class: "btn btn-dark nav_margin" %>
          </li>
          <li class="nav-item li_margin">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn btn-dark nav_margin margin_right_footer" %>
          </li>

        </ul>
        <div class="">
          <%=  search_form_for(@q, url:items_path) do |f|%>
          <%= f.label '' %>
          <%= f.search_field :name_cont,:placeholder => "商品名"%>
          <%= f.submit :検索 %><br>
          <% end %>
        </div>
      </div>
      <% else %>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto"></ul>
        <ul class="navbar-nav mt-2 mt-lg-0">
          <li class="nav-item li_margin">
            <%= link_to "ホーム", root_path, class: "btn btn-dark nav_margin"%>
          </li>
          <li class="nav-item li_margin">
            <%= link_to "ログイン", new_user_session_path, class: "btn btn-dark" %>
          </li>
          <li class="nav-item li_margin">
            <%= link_to "新規作成", new_user_registration_path, class: "btn btn-dark margin_right_footer" %>
          </li>

        </ul>
        <div class="">
          <%=  search_form_for(@q, url:items_path) do |f|%>
          <%= f.label '' %>
          <%= f.search_field :name_cont,:placeholder => "商品名"%>
          <%= f.submit :検索 %><br>
          <% end %>
        </div>
      </div>
      <% end %>
    </nav>
  </header>

  <article>
    <%= yield %>
  </article>
  <div id="page_top"><a href="#"></a></div>
  <div class="block_30"></div>
  <%= render 'users/footer' %>

</body>

</html>